facebook_prj/core/urls.py
from django.urls import path

from core import views

app_name = "core"

urlpatterns = [
    path("", views.index, name = "feed"),
    path("post/<slug:slug>/", views.post_detail, name = "post-detail"),
    path("create-post/", views.create_post, name = "create-post"),
    path("like-post/", views.like_post, name = "like-post"),
    path("comment-post/", views.comment_on_post, name = "comment-post"),
    path("like-comment/", views.like_comment, name = "like-comment"),
    path("reply-comment/", views.reply_comment, name = "reply-comment"),
    path("delete-comment/", views.delete_comment, name = "delete-comment"),
    path("delete-reply/", views.delete_reply, name = "delete-reply"),
    path("add-friend/", views.add_friend, name = "add-friend"),
    path("accept-friend-request/",views.accept_friend_request, name = "accept-friend-request"),
    path("reject-friend-request/",views.reject_friend_request, name = "reject-friend-request"),
    path("unfriend/", views.unfriend, name = "unfriend"),

]

facebook_prj/facebook_prj/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path("user/",include("userauths.urls") ),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

facebook_prj/userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"


urlpatterns = [
    path("sign-up/", views.RegisterView, name = "sign-up"),
    path("sign-in/", views.LoginView, name = "sign-in"),
    path("sign-out/", views.LogoutView, name = "sign-out"),

    path("my-profile/", views.my_profile, name = "my-profile"),

    path("profile/<username>", views.friend_profile, name  = "profile"),

]

facebook_prj/userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from PIL import Image
from shortuuid.django_fields import ShortUUIDField
from django.db.models.signals import post_save
from django.utils.text import slugify
import shortuuid

# Create your models here.

GENDER = (
    ("male", "Male"),
    ("female", "Female")
)

RELATIONSHIP = (
    ("single", "Single"),
    ("married", "Married")
)


def user_directory_path(instance, filename):
    ext = filename.split(".")[-1]
    filename = "%s.%s" % (instance.user.id, ext),
    return 'user_{0}/{1}'.format(instance.user.id, filename)


class User(AbstractUser):
    full_name = models.CharField(max_length=200)
    username = models.CharField(max_length=100)
    email = models.EmailField(unique = True)
    phone = models.CharField(max_length=200)
    gender = models.CharField(max_length=100, choices = GENDER)

    otp = models.CharField(max_length=10, null = True, blank = True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username
    



class Profile(models.Model):
    pid = ShortUUIDField(length = 7, max_length=25, alphabet = 'abcdefghijklmnopqrstuvwxyz')
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cover_image = models. ImageField(upload_to = user_directory_path, blank= True, null = True,default = "cover.jpg")
    image = models.ImageField(upload_to = user_directory_path, blank= True, null = True, default = "default.png")
    full_name = models.CharField(max_length=200, null= True, blank = True)
    phone = models.CharField(max_length=200, null = True, blank = True)
    gender = models.CharField(max_length=100, choices = GENDER, default = "male")
    relationship = models.CharField(max_length=100, choices=RELATIONSHIP, default = "single")
    bio = models.CharField(max_length=200, null = True, blank = True)
    about_me = models.TextField(null = True, blank = True)
    country = models.CharField(max_length=200, null = True, blank = True)
    state = models.CharField(max_length=200, null = True, blank = True)
    city = models.CharField(max_length=200, null = True, blank = True)
    address = models.CharField(max_length=200, null = True, blank = True)
    working_at = models.CharField(max_length=200, null = True, blank = True)
    instagram = models.CharField(max_length=200, null = True, blank = True)
    whatsapp = models.CharField(max_length=200, null = True, blank = True)
    verified = models.BooleanField(default = False)
    followers =models.ManyToManyField(User, null = True, blank = True, related_name = "followers")
    following =models.ManyToManyField(User, null = True, blank = True, related_name = "following")
    friends =models.ManyToManyField(User, null = True, blank = True, related_name = "friends")
    blocked = models.ManyToManyField(User, null = True, blank = True, related_name = "blocked")
    date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique = True, null = True, blank = True)

    def __str__(self):
        return self.user.username
    
    def save(self, *args, **kwargs):
        if self.slug == "" or self.slug == None:
            uuid_key = shortuuid.uuid()
            uniqueid = uuid_key[:2]
            self.slug = slugify(self.full_name)+ '-'+ str(uniqueid.lower())
        super(Profile, self).save(*args, **kwargs)




def create_user_profile(sender, instance, created, **Kwargs):
    if created:
        Profile.objects.create(user = instance)


def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

post_save.connect(create_user_profile, sender = User)
post_save.connect(save_user_profile, sender = User)

facebook_prj/userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User


class UserRegisterForm(UserCreationForm):
    full_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={"placeholder": "Full Name" ,"class":"form-control"}), required = True)    
    username = forms.CharField(widget = forms.TextInput(attrs = { 'class' : 'id form-control', 'placeholder': 'User Name'}), max_length = 100, required = True)
    phone = forms.CharField(max_length=15, widget=forms.TextInput(attrs={"class" : "id form-control","placeholder": "Phone"}), required = True)
    email = forms.CharField(widget = forms.TextInput(attrs = {'class' : 'id form-control', 'placeholder': 'Email Address'}), required = True)    
    password1 = forms.CharField(widget = forms.PasswordInput(attrs = {'class' : 'id form-control', 'placeholder': 'Password'}), required = True)
    password2 = forms.CharField(widget = forms.PasswordInput(attrs = {'class' : 'id form-control', 'placeholder': 'Confirm password'}), required = True)



    class Meta:
        model = User
        fields = ['full_name', 'username', 'email','phone','gender','password1', 'password2']

facebook_prj/userauths/views.py
from django.shortcuts import render, redirect
from userauths.forms import UserRegisterForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from userauths.models import Profile, User
from django.http import HttpResponseRedirect


from core.models import Post, FriendRequest


# Create your views here.


def RegisterView(request):
    if request.user.is_authenticated:
        messages.warning(request, "You are registered!")
        return redirect("core:feed")
    

    form = UserRegisterForm(request.POST or None)

    if form.is_valid():
        user = form.save()

        full_name = form.cleaned_data.get("full_name")
        phone = form.cleaned_data.get("phone")
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password1")

        user = authenticate(email = email, password = password)

        if user:
            login(request, user)

            profile = Profile.objects.get(user = request.user)
            profile.full_name = full_name
            profile.phone = phone
            profile.save()

            messages.success(request, f"Hi, {full_name}, your account was created successfully")
            return redirect("core:feed")
        else:
            messages.error(request, "Authentication failed. Please try again.")
    else:
        print(form.errors)
        messages.error(request, "There was an error with your form. Please check your input.")
    

    context = {
        "form" : form
    }

    return render(request, "userauths/sign-up.html", context)







def LoginView(request):
    if request.user.is_authenticated:
        messages.warning(request, "You are already login!")
        return redirect("core:feed")
    
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        try:
            user = User.objects.get(email = email)
            user = authenticate(request, email = email, password = password)
            if user is not None:
                login(request,user)
                messages.success(request, "You are logged in")
                return redirect("core:feed")
            
            else:
                messages.error(request, "Username or password does not match")
                return redirect("userauths:sign-up")

        except:
            messages.error(request, "User does not exist")
            return redirect("userauths:sign-up")

    return HttpResponseRedirect("/")





def LogoutView(request):
    logout(request)
    messages.success(request, "You are looged out!")
    return redirect("userauths:sign-up")



@login_required
def my_profile(request):
    profile = request.user.profile
    posts = Post.objects.filter(active = True, user = request.user)

    context = {
        "profile" : profile,
        "posts": posts,
    }

    return render(request, "userauths/my-profile.html", context)




@login_required
def friend_profile(request, username):
    profile = Profile.objects.get(user__username = username)
    posts = Post.objects.filter(active = True, user = profile.user)

    bool = False
    bool_friend = False

    sender = request.user
    receiver = profile.user

    try:
        friend_request = FriendRequest.objects.get(sender = sender , receiver = receiver)
        if friend_request:
            bool = True

        else:
            bool = False

    except:
        bool = False



    context = {
        "profile": profile,
        "posts": posts,
        "bool": bool,
    }


    return render(request, "userauths/friend-profile.html", context)

facebook_prj/templates/userauths/sign-up.html
{% comment %} <form action = "" method = "POST">
    {% csrf_token %}
    {{banana.as_p}}
    <button type = "submit"> Create account</button>
</form> {% endcomment %}

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Facebook Login</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="facebook_prj/static/login.css">
</head>
<body>
    <div class="container-fluid">
        <div class="row no-gutters">
            <div class="col-md-6 d-flex justify-content-center align-items-center left-side">
                <div class="text-center">
                    <h1 class="display-1 text-primary">facebook</h1>
                    <p class="lead">Connect with friends and the world around you on Facebook.</p>
                </div>
            </div>
            <div class="col-md-6 d-flex justify-content-center align-items-center right-side">
                <div class="login-form">
                    <form method = "POST" action = "{% url 'userauths:sign-in' %}" >
                        {%csrf_token%}
                        
                        <div class="form-group">
                            <input type="email" name = "email" class="form-control" id="email" placeholder="Email address "   autocomplete="off" >
                        </div>
                        <div class="form-group">
                            <input type="password" name = "password" class="form-control" id="password" placeholder="Password"  autocomplete="off" >
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Log In</button>
                        <div class="text-center mt-3">
                            <a href="#">Forgotten password?</a>
                        </div>
                        <hr>
                        <div class="text-center">
                            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#registerModal">Create New Account</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="registerModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="registerModalLabel">Sign Up</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method = "POST">
                        {%csrf_token%}
                        <div class="form-group">
                            {{form.full_name}}
                            
                        </div>
                        <div class="form-group">
                            {{form.username}}
                            
                        </div>
                        <div class="form-group">
                            {{form.email}}
                            
                        </div>

                        <div class="form-group">
                            {{form.password1}}
                            
                        </div>

                        <div class="form-group">
                            {{form.password2}}
                            
                        </div>

                        <div class="form-group">
                            {{form.gender}}
                            
                        </div>

                        <div class="form-group">
                            {{form.phone}}
                            
                        </div>
                        
                        <button type="submit" class="btn btn-primary btn-block">Sign Up</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>